cd /data/data/com.sdt.sdtas/files/sdtas/lib
ln -sf libASFunction.so.1.2.0.27 libASFunction.so.1
ln -sf libASFunction.so.1 libASFunction.so
ln -sf libAuthClient.so.1.0.0.27 libAuthClient.so.1
ln -sf libAuthClient.so.1 libAuthClient.so
ln -sf libdccp_naclient.so.1.0.0.27 libdccp_naclient.so.1
ln -sf libdccp_naclient.so.1 libdccp_naclient.so
ln -sf libGeneralDS.so.1.0.5.11 libGeneralDS.so.1
ln -sf libGeneralDS.so.1 libGeneralDS.so
ln -sf libGeneralMisc.so.2.0.5.8 libGeneralMisc.so
ln -sf libidauth_client_sdk.so.1.0.0.19 libidauth_client_sdk.so.1
ln -sf libidauth_client_sdk.so.1 libidauth_client_sdk.so
ln -sf libLocalProxyDyn.so.1.0.0.13 libLocalProxyDyn.so.1
ln -sf libLocalProxyDyn.so.1 libLocalProxyDyn.so
ln -sf libNAClientFunc.so.1.0.0.82 libNAClientFunc.so.1
ln -sf libNAClientFunc.so.1 libNAClientFunc.so
ln -sf libNAConfig.so.1.0.0.79 libNAConfig.so.1
ln -sf libNAConfig.so.1 libNAConfig.so
ln -sf libPackcs_311KEY.so.1.0.1.16 libPackcs_311KEY.so.1
ln -sf libPackcs_311KEY.so.1 libPackcs.so
ln -sf libSDTAuth.so.1.0.2.15 libSDTAuth.so.1
ln -sf libSDTAuth.so.1 libSDTAuth.so
ln -sf libSDTcrypto.so.1.0.1.8 libSDTcrypto.so
ln -sf libSDTEngine.so.1.0.2.8 libSDTEngine.so
ln -sf libSDTJSON.so.1.0.0.14 libSDTJSON.so.1
ln -sf libSDTJSON.so.1 libSDTJSON.so
ln -sf libsdtmqac.so.1.0.3.3 libsdtmqac.so.1
ln -sf libsdtmqac.so.1 libsdtmqac.so
ln -sf libsmcipher.so.1.0.0.6 libsmcipher.so.1
ln -sf libsmcipher.so.1 libsmcipher.so
ln -sf libSocksServer.so.2.2.6.1 libSocksServer.so.2
ln -sf libSocksServer.so.2 libSocksServer.so
ln -sf libtlspp240.so.1.0.1.12 libtlspp240.so.1
ln -sf libtlspp240.so.1 libtlspp240.so
ln -sf libtlspp311.so.1.0.1.7 libtlspp311.so.1
ln -sf libtlspp311.so.1 libtlspp311.so
ln -sf libwhk2uk.so.1.0.1.21 libwhk2uk.so.1
ln -sf libwhk2uk.so.1 libwhk2uk.so
ln -sf libwsutil.so.1.3.0.2 libwsutil.so.1
ln -sf libwsutil.so.1 libwsutil.so
ln -sf libXTEngine.so.1.0.0.10 libXTEngine.so
ln -sf libYWT_general.so.1.1.3.18 libYWT_general.so
ln -sf libusbwhsdk.so libwhsdk.so
ln -sf DCContainer-1.0.0.7 DCContainer
ln -sf NAClient-1.0.0.82 NAClient
ln -sf sdtmqb-1.0.3.2 sdtmqb
chmod -R 777 packcs.pid DCContainer-1.0.0.7 NAClient-1.0.0.82 sdtmqb-1.0.3.2